_target_: src.models.sasrec_I.SASRecItem

name: sasrec_I
hidden_size: 96
num_blocks: 2
num_heads: 2
dropout: 0.2
seq_len: 300
n_epochs: 600
lr: 0.0016558741628668475

batch_size: 256
patience_per_epoch: 1

val_top_n: 10
filter_seen: true
device: cuda
k_neighbors: 5
gamma: 0.45
