- name: k
  type: categorical
  choices:
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
    - 8192
    - 16384
    - 32768

- name: lap_proj_mode
  type: categorical
  choices:
    - mlp

- name: lap_proj_num_layers
  type: categorical
  choices:
    - 1
    - 2
    - 3
    - 4

- name: lap_proj_hidden_mult
  type: categorical
  choices:
    - 1.0
    - 2.0
    - 4.0

- name: lap_proj_activation
  type: categorical
  choices:
    - gelu
    - relu
    - silu

- name: lap_proj_layer_norm
  type: categorical
  choices:
    - false
    - true

- name: use_input_lpe
  type: categorical
  choices:
    - true

- name: use_output_lpe
  type: categorical
  choices:
    - false

- name: learn_lpe_gates
  type: categorical
  choices:
    - false

- name: input_lpe_gate
  type: categorical
  choices:
    - 0.0
    - 0.25
    - 0.5
    - 1.0
    - 2.0
    - 4.0
