- name: lr
  type: float
  low: 1e-5
  high: 1e-3

- name: hidden_size
  type: categorical
  choices:
    - 32
    - 64

- name: num_heads
  type: categorical
  choices:
    - 1

- name: dropout
  type: float
  log: false
  low: 0.0
  high: 0.5
  step: 0.1

- name: batch_size
  type: categorical
  choices:
    - 8
    - 16
    - 32

- name: seq_len
  type: categorical
  choices:
    - 50
    - 100

- name: num_blocks
  type: int
  low: 1
  high: 2
  step: 1

- name: loss_type
  type: categorical
  choices:
    - sampled

- name: num_negatives
  type: categorical
  choices:
    - 128
    - 256
