- name: hidden_size
  type: int
  low: 64
  high: 128
  step: 32

- name: num_blocks
  type: int
  low: 1
  high: 4
  step: 1

- name: num_heads
  type: categorical
  choices:
    - 1
    - 2
    - 4

- name: dropout
  type: float
  log: false
  low: 0.0
  high: 0.5
  step: 0.1

- name: lr
  type: float
  low: 1e-4
  high: 3e-3

- name: k_neighbors
  type: categorical
  choices:
    - 1
    - 5
    - 10
    - 25
    - 50
    - 75
    - 100
    - 150
    - 210
    - 300
- name: gamma
  type: float
  log: false
  low: 0.0
  high: 1
  step: 0.05

