- name: lap_proj_mode
  type: categorical
  choices:
    - identity

- name: use_input_lpe
  type: categorical
  choices:
    - true

- name: use_output_lpe
  type: categorical
  choices:
    - false

- name: use_absolute_pos_emb
  type: categorical
  choices:
    - false

- name: use_item_emb_scale
  type: categorical
  choices:
    - false
