defaults:
  - dataset: MovieLens-1M
  - model: sasrec_mlp
  - metrics: base
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${model.name}__${dataset.name}__${now:%H-%M-%S}
  sweep:
    dir: outputs/sweeps/${now:%Y-%m-%d}/${model.name}__${dataset.name}__${now:%H-%M-%S}

seed: 42
max_top_n: 100

model:
  lr: 0.006770186482827876
  hidden_size: 128
  num_heads: 2
  dropout: 0.2
  batch_size: 128
  num_blocks: 2
  seq_len: 200
  filter_seen: true
  max_patience: 10
  lap_eigvec_path: MovieLens-1M_eigvecs.npy
  lap_project_chunk_size: 1024
  item_chunk_size: 2048
