defaults:
  - dataset: Amazon2014-Sports-And-Outdoors
  - model: sasrec_lap_attention_bias
  - metrics: base
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${model.name}__${dataset.name}__${now:%H-%M-%S}
  sweep:
    dir: outputs/sweeps/${now:%Y-%m-%d}/${model.name}__${dataset.name}__${now:%H-%M-%S}

seed: 42
max_top_n: 100

model:
  name: sasrec_lap_attention_bias_sports_tuned
  seed: 42
  device: cuda
  lr: 0.005452572110078795
  n_epochs: 1000
  hidden_size: 128
  num_blocks: 1
  num_heads: 1
  dropout: 0.4
  seq_len: 200
  batch_size: 512
  filter_seen: true
  max_patience: 10
  k: 128
  lap_eigvec_path: Amazon2014-Sports-And-Outdoors_eigvecs.npy
  lap_bias_dim: 32
  position_encoding: rope
  lap_bias_mode: cosine
  lap_gate_init: -3.0
  rope_base: 10000.0

