defaults:
  - dataset: Amazon2014-Clothing-Shoes-And-Jewelry
  - metrics: base
  - _self_

model:
  _target_: src.models.SASRecRoPE
  name: sasrec_rope_clothing
  seed: 42
  device: cuda
  lr: 0.00021124444422497844
  n_epochs: 1000
  hidden_size: 512
  num_blocks: 2
  num_heads: 1
  dropout: 0.30000000000000004
  seq_len: 200
  batch_size: 256
  filter_seen: true
  max_patience: 10
  rope_base: 10000.0

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${model.name}__${dataset.name}__${now:%H-%M-%S}
  sweep:
    dir: outputs/sweeps/${now:%Y-%m-%d}/${model.name}__${dataset.name}__${now:%H-%M-%S}

seed: 42
max_top_n: 100
